EPC network elements (mme_gw, mme, spgw, hss) can be run as daemons (catched freeDiameter logs), this may facilitate the run of test scenarios.

diff --git a/BUILD/TOOLS/build_helper b/BUILD/TOOLS/build_helper
--- a/BUILD/TOOLS/build_helper
+++ b/BUILD/TOOLS/build_helper
@@ -226,6 +226,7 @@ install_netmap() {
     linux-source \
     qt4-dev-tools
 
+  $SUDO  apt-get build-dep linux-image-$(uname -r)
   if [ $1 -eq 0 ]; then
     read -p "Do you want to install netmap ? <y/N> " prompt
   else
@@ -1265,3 +1266,45 @@ do
 done
 }
 
+
+###################################
+# Daemon start stop
+###################################
+function do_start_daemon()
+{
+  # Return
+  #   0 if daemon has been started
+  #   1 if daemon was already running
+  #   2 if daemon could not be started
+  $SUDO start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+    || return 1
+  $SUDO start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+    $DAEMON_ARGS \
+    || return 2
+  # Add code here, if necessary, that waits for the process to be ready
+  # to handle requests from services started subsequently which depend
+  # on this one.  As a last resort, sleep for some time.
+}
+
+function do_stop_daemon()
+{
+  # Return
+  #   0 if daemon has been stopped
+  #   1 if daemon was already stopped
+  #   2 if daemon could not be stopped
+  #   other if a failure occurred
+  $SUDO start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+  RETVAL="$?"
+  [ "$RETVAL" = 2 ] && return 2
+  # Wait for children to finish too if this is a daemon that forks
+  # and if the daemon is only ever run from this initscript.
+  # If the above conditions are not satisfied then add some other code
+  # that waits for the process to drop all resources that could be
+  # needed by services started subsequently.  A last resort is to
+  # sleep for some time.
+  $SUDO start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+  [ "$?" = 2 ] && return 2
+  # Many daemons don't delete their pidfiles when they exit.
+  $SUDO rm -f $PIDFILE
+  return "$RETVAL"
+}
